import fp from 'fastify-plugin';
import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { eq } from 'drizzle-orm';
import { Type } from '@sinclair/typebox';
import PDFDocument from 'pdfkit';
import { users, documents, tokenLedger } from '../../db/schema.js';
import { CREDIT_COSTS } from '../../lib/creditCosts.js';

const GeneratePdfBody = Type.Object({
  title: Type.String({ minLength: 1 }),
  content: Type.Object({
    sections: Type.Array(
      Type.Object({
        heading: Type.String(),
        body: Type.String(),
      }),
    ),
  }),
  template: Type.Optional(
    Type.Union([
      Type.Literal('permit'),
      Type.Literal('grant'),
      Type.Literal('license'),
      Type.Literal('general'),
    ]),
  ),
});

const PDF_COST = CREDIT_COSTS.pdfExport;

export default fp(async (app: FastifyInstance) => {
  // ─── Generate PDF ───
  app.post(
    '/api/pdf/generate',
    { schema: { tags: ['pdf'], body: GeneratePdfBody } },
    async (request: FastifyRequest, reply: FastifyReply) => {
      const userId = request.authUser!.sub;
      const body = request.body as {
        title: string;
        content: { sections: Array<{ heading: string; body: string }> };
        template?: string;
      };

      // Check token balance
      const [user] = await app.db
        .select()
        .from(users)
        .where(eq(users.id, userId))
        .limit(1);

      if (!user) {
        return reply.status(404).send({ detail: 'User not found' });
      }

      if (user.tokenBalance < PDF_COST) {
        return reply.status(402).send({
          detail: `PDF generation requires ${PDF_COST} tokens. You have ${user.tokenBalance}.`,
        });
      }

      // Generate PDF
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));

      // Header
      doc.rect(0, 0, doc.page.width, 80).fill('#1e40af');

      doc
        .fontSize(22)
        .fillColor('#ffffff')
        .text('MyBuddy', 50, 25, { align: 'left' })
        .fontSize(10)
        .text('AI-Generated Document', 50, 52, { align: 'left' });

      // Title
      doc
        .fillColor('#0f172a')
        .fontSize(18)
        .text(body.title, 50, 110)
        .moveDown(0.5);

      // Date
      doc
        .fontSize(10)
        .fillColor('#64748b')
        .text(`Generated: ${new Date().toLocaleDateString()}`, 50, doc.y)
        .moveDown(1);

      // Sections
      for (const section of body.content.sections) {
        doc
          .fontSize(14)
          .fillColor('#1e40af')
          .text(section.heading)
          .moveDown(0.3)
          .fontSize(11)
          .fillColor('#334155')
          .text(section.body, { lineGap: 4 })
          .moveDown(1);
      }

      // Footer
      doc
        .fontSize(8)
        .fillColor('#94a3b8')
        .text(
          'This document was generated by MyBuddy AI Assistant. Please verify all information.',
          50,
          doc.page.height - 50,
          { align: 'center' },
        );

      doc.end();

      // Wait for PDF to complete
      const pdfBuffer = await new Promise<Buffer>((resolve) => {
        doc.on('end', () => resolve(Buffer.concat(chunks)));
      });

      // Deduct tokens
      await app.db
        .update(users)
        .set({ tokenBalance: user.tokenBalance - PDF_COST })
        .where(eq(users.id, userId));

      await app.db.insert(tokenLedger).values({
        userId,
        changeAmount: -PDF_COST,
        reason: 'pdf_fee',
      });

      // Save document record
      const [docRecord] = await app.db
        .insert(documents)
        .values({
          userId,
          imageUrl: '',
          aiSummary: body.title,
          docType: body.template || 'other',
          paidAmount: '5.00',
        })
        .returning();

      // Send PDF
      reply.header('Content-Type', 'application/pdf');
      reply.header(
        'Content-Disposition',
        `attachment; filename="mybuddy-${docRecord.id}.pdf"`,
      );
      return reply.send(pdfBuffer);
    },
  );
});
